# Generated by Django 4.1.3 on 2022-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0002_modelsnapshot_d_loss_svg_modelsnapshot_g_loss_svg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='data_fast_wav',
        ),
        migrations.RemoveField(
            model_name='model',
            name='data_first_slice',
        ),
        migrations.RemoveField(
            model_name='model',
            name='data_normalize',
        ),
        migrations.RemoveField(
            model_name='model',
            name='data_pad_end',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_fast_wav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_first_slice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_normalize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_pad_end',
            field=models.BooleanField(default=False),
        ),
    ]
