# Generated by Django 4.1.3 on 2022-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0009_alter_library_path_alter_modelrun_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsnapshot',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
