# Generated by Django 4.1.3 on 2022-11-09 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0012_rename_path_dataset_data_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsnapshot',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='wavegan_genr_wgangp_beta1',
            field=models.FloatField(default=0.5, help_text='Adam optimizer beta1 for generator.'),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='wavegan_genr_wgangp_beta2',
            field=models.FloatField(default=0.9, help_text='Adam optimizer beta2 for generator.'),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='wavegan_genr_wgangp_learn',
            field=models.FloatField(default=0.0001, help_text='Initial learning rate for generator.'),
        ),
    ]
