# Generated by Django 4.1.3 on 2022-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0014_alter_modelsnapshot_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsnapshot',
            name='size_gb',
            field=models.IntegerField(default=0),
        ),
    ]
