# Generated by Django 4.1.3 on 2022-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0018_remove_modelsnapshot_size_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsnapshot',
            name='size_gb',
            field=models.IntegerField(default=0),
        ),
    ]
