# Generated by Django 4.1.3 on 2022-11-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0019_modelsnapshot_size_gb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsnapshot',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='modelsnapshot',
            name='size_gb',
        ),
    ]
