# Generated by Django 4.1.3 on 2022-11-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0021_modelsnapshot_creation_time_modelsnapshot_size_gb'),
    ]

    operations = [
        migrations.CreateModel(
            name='x_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=2048)),
                ('token', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='modelsnapshot',
            name='size_gb',
            field=models.FloatField(default=0.0),
        ),
    ]
