# Generated by Django 4.1.3 on 2022-11-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0022_x_message_alter_modelsnapshot_size_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='training_node_affinity',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='x_message',
            name='token',
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
