# Generated by Django 4.1.3 on 2022-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0024_alter_x_message_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='node_affinity',
            field=models.CharField(default='ubuntu-wavegan-2222', max_length=128),
        ),
    ]
