# Generated by Django 4.1.3 on 2022-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0025_library_node_affinity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrun',
            old_name='training_node_affinity',
            new_name='node_affinity',
        ),
        migrations.AlterField(
            model_name='library',
            name='path',
            field=models.CharField(help_text='Filesystem path relative to settings.NODE_STORAGE_ROOT', max_length=255, unique=True),
        ),
    ]
