# Generated by Django 4.1.3 on 2022-11-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0026_rename_training_node_affinity_modelrun_node_affinity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='node_affinity',
            field=models.CharField(blank=True, default='ubuntu-wavegan-2222', max_length=128),
        ),
    ]
