# Generated by Django 4.1.3 on 2023-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wganbrowser', '0029_alter_dataset_data_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='data_slice_len',
            field=models.IntegerField(choices=[(65536, '65536'), (32768, '32768'), (16384, '16384')], default=65536, help_text='Slice length of audio used when training and length of generated audio samples. In samples.'),
        ),
    ]
